---
- name: Configure Nagios Server
  hosts: nagios
  become: yes

  tasks:
    - name: Copy config file for Exxomm servers
      copy:
        src: exomm.cfg
        dest: /etc/nagios4/conf.d/exxomm.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nagios to apply new config
      service:
        name: nagios4
        state: restarted