# purpose
# exxomm-fe/nginx.conf (in the FE container)

# Designed to serve static frontend (root /usr/share/nginx/html;, try_files ... /index.html) — typical SPA container.

# Only /api requests are proxied to a backend (service name backend or IP).

# This Nginx is packaged with the frontend image and meant to run next to the app (inside container or docker-compose).


 server {
   # Listen on the container's port 80
   listen 80;
 
   # Set the root directory for the React app
   root /usr/share/nginx/html;
   # This makes React's routing work
   index index.html index.htm;
 
   # --- THIS IS THE REVERSE PROXY ---
   # Any request to /api/... will be sent to your backend
   location /api {

   # for Docker Compose/ Docker build environments, we can use the service name 'backend'(in docker-compose.yml)
     # proxy_pass http://backend:<backend_port_no>;


 # for direct IP access, use the private IP of the backend server
     proxy_pass http://10.0.1.165:8000;
   
     proxy_http_version 1.1;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forwarded-Proto $scheme;
     proxy_set_header Host $host;
     proxy_redirect off;

   }
 
   # This makes sure all other requests go to your React app
   location / {
     try_files $uri $uri/ /index.html;
   }
 }


