
# Set up the Nginx server
server {
  # Listen on the container's port 80
  listen 80;
  
  # Set the root directory for the React app
  root /usr/share/nginx/html;
  # This makes React's routing work
  index index.html index.htm;
  
  # --- THIS IS THE REVERSE PROXY ---
  # Any request to /api/... will be sent to your backend
  location /api {
    # Replace this IP with your backend's PRIVATE IP


  # for Docker Compose/ Docker build environments, we can use the service name 'backend'(in docker-compose.yml)
    # proxy_pass http://backend:3000;


# for direct IP access, use the private IP of the backend server
    proxy_pass http://10.0.1.119:3000;
    
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
  
  # This makes sure all other requests go to your React app
  location / {
    try_files $uri $uri/ /index.html;
  }
}